AllCops:
  TargetRubyVersion: '2.6'
  Exclude:
    - 'testable_snippets/**/*'
    - '*/testable_snippets/**/*'
    - 'tools/**/*'
    - 'twilio-api-faker/**/*'
Style/FileName:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
